### PR TITLE
Search Bar Functionality

### PR DESCRIPTION
**Pull request by adriangmweb**
### Does it solve any issue? if yes, then mention the issue here.

Now the navbar search bar is working.

I have also change some components and set the app state to be able to change it and add more features in the future.

### CODE REVIEW

**Comment by adriangmweb** [comment]
I just fixed some conflicts with the last version. App is ready to go! :rocket: 

I'm enjoying a lot contributing here, I had React a little bit oxidated :smiley:

**Comment by drex44** [comment]
@adriangmweb great. the search is working amazing but if we add FoodCard directly in Layout.js then we cannot use it everywhere. Layout.js is for using it as a higher order layout component (HOC).

Because of this about page is not working properly. and all other pages where we will use Layout.js will also not work.

ToDo: Can you move the login to the index.js. 

we are following component, a container system for react components. 
the components being only UI component and containers having all the data fetch and process login.

**Review by drex44 — COMMENTED** [review]
do not change the layout.js and move the login to index.js instead of layout.js.

**Comment by drex44** [comment]
@adriangmweb glad to hear it! hope you enjoy contributing more! you have been a great help!

**Pull request merged**
