### PR TITLE
Added food details page

### LINKED ISSUE #4: FrontEnd: Create a new simple page
This is react/ nextjs webapp.

If you go to the home page then it shows a learn more button. clicking on it should show a page with more details.

so create a simple component called detailedFoodDetails.js that shows the title of the disease passed. you can follow the instruction given [here](https://nextjs.org/learn/basics/create-dynamic-pages/adding-a-list-of-posts)

Read the readme.md for more information or comment if you need more information or help!

### PR DESCRIPTION
**Pull request by codegagan**
Fixes #4 
Added the page which can be seen with learn more button.
#Hacktoberfest

### CODE REVIEW

**Comment by drex44** [comment]
Hi, @codegagan can you resolve the conflict and then add a commit on this?

**Comment by codegagan** [comment]
I don't have write access, I think. so cannot resolve conflict.

**Comment by codegagan** [comment]
The diff is clean though, I think you can just resolve the conflict. https://github.com/drex44/good-food-guide/pull/15/files

**Comment by drex44** [comment]
merged!
@codegagan Thanks for the PR.

**Pull request merged**
