### PR TITLE
Add details page

### PR DESCRIPTION
**Pull request by adriangmweb**
### Does it solve any issue? if yes, then mention the issue here.
Solves -> FrontEnd: Create a new simple page #4

### CODE REVIEW

**Comment by drex44** [comment]
@adriangmweb, sorry :(
but somebody already submitted a PR on this and it's merged.
He commented on the issue that he was working on this.
would be interested in working on this #6 ?
apparently, #5 will be completed pretty soon. if you're interested then I will assign it to you?

again sorry! :(

**Comment by adriangmweb** [comment]
Oh sorry I didn't check it :sweat_smile: 
I won't be coding more for the day so leave it for another person and I'll grab one tomorrow :wink:

**Comment by drex44** [comment]
@adriangmweb okay, thanks, man. Btw if you feel like you can improve the site anyway then feel free to create a new issue and work on it. :)

I will discard other two files and merge the Contributors.md from this PR.

**Comment by drex44** [comment]
Thanks, @adriangmweb for the PR.

**Pull request merged**
